# =============================================================================
# MLDEPLOY v0.0.0 - Configuration File
# -----------------------------------------------------------------------------
# Comments below describe available configuration options.
# Uncomment and add details as needed to suit your project.
# 
# Contents:
#   1. Environment details
#     1.1. Python version
#     1.2. Base docker image
#   2. Program setup
#     2.1. Main execution file
#     2.2. Files and folders to copy or clone
#
# -----------------------------------------------------------------------------
# Author: kingfischer16 (https://github.com/kingfischer16/mldeploy)
# =============================================================================

project-name: 


# 1. Environment details.
# -----------------------------------------------------------------------------
# 1.1. Python version.
python-version: 3.8

# 1.2 Base docker image.
base-image: debian:slim-buster


# 2. Program setup.
# -----------------------------------------------------------------------------
# 2.1. Main execution file.
main-file: 

# 2.2. Files and folders to copy or clone
add-files:
   - /home/folder1
#   - https://github.com/my-repo.git

# 2.3. Custom Dockerfile
# Path to a Dockerfile that you wish to use instead of building
# one using the CLI.
docker-file: python3.8:alpine3.11
