# =============================================================================
# MLDEPLOY v0.0.0 - Configuration File
# -----------------------------------------------------------------------------
# Comments below describe available configuration options.
# Uncomment and add details as needed to suit your project.
# 
# Contents:
#   1. Environment details
#     1.1. Python version
#     1.2. Base docker image
#   2. Program setup
#     2.1. Main execution file
#     2.2. Files and folders to copy or clone
#   3. Docker options
#     3.1. Custom Dockerfile
#
# -----------------------------------------------------------------------------
# Author: kingfischer16 (https://github.com/kingfischer16/mldeploy)
# =============================================================================

project-name: my-app


# 1. Environment details.
# -----------------------------------------------------------------------------
# 1.1. Python version.
python-version: 3.8

# 1.2 Base docker image.
base-image: debian:slim-buster


# 2. Program setup.
# -----------------------------------------------------------------------------
# 2.1. Main execution file.
main-file:

# 2.2. Files and folders to copy or clone
#add-files:
#   - /home/folder1
#   - https://github.com/my-repo.git


# 3. Docker options.
# -----------------------------------------------------------------------------
# 3.1. Custom Dockerfile
# Path to a Dockerfile that you wish to use instead of building
# one using the CLI. Overrides the building of the file.
docker-file: /home/folder2/docks/Dockerfile

# 3.2. Custom Docker image
# Name of the Docker image you with to use intead of building
# one using the CLI. Overrides the building of the Dockerfile and
# Docker image.
# If a ':' character is included the name must be enclosed in
# quotation marks.
docker-image: my_docker_image:2020-tag
